### ISSUE TITLE
Dart 2 runtime errors in tests 

### ISSUE THREAD

**Issue by keertip** [dart-lang/package_resolver#10]
running tests in dart 2 mode,

type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, Uri>' where...
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, Uri>' where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core
  Uri is from dart:core
../../package_resolver/test/current_isolate_info_test.dart 56:45  main.<fn>.<fn>

**Comment by nex3** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/33028

**Comment by keertip** [comment]
@nex3 , the sdk issue is fixed.
