### ISSUE TITLE
Errors in 1.10.0 on Dart 2.1.0

### ISSUE THREAD

**Issue by todbachman-wf** [dart-lang/package_resolver#26]
I'm running Dart version `2.1.0` and encounter these errors with version `1.10.0` of package_resolver:

```
Error compiling dartdevc module:package_resolver|lib/package_resolver.ddc.js

[error] The imported library ''current_isolate_resolver_stub.dart'' can't have a part-of directive. (package:package_resolver/src/package_resolver.dart, line 12, col 8)
[error] The imported library ''utils_isolate_stub.dart'' can't have a part-of directive. (package:package_resolver/src/utils.dart, line 15, col 8)

Please fix all errors before compiling (warnings are okay).
```

Pinning to the previous release (`1.9.0`) resolves the issue.

I just upgraded to Dart `2.1.1` and that also resolves this issue. This makes me think the sdk range for the latest release should be `>=2.1.1 <3.0.0`.

**Comment by evanweible-wf** [comment]
~Upgrading `build_resolvers` to at least `1.0.3` fixes this issue (see https://github.com/dart-lang/package_resolver/issues/23).~

The fix was actually in build_modules 1.0.8 - see https://github.com/dart-lang/sdk/issues/36264#issuecomment-474640754

**Comment by kevmoo** [comment]
@jmesserly – can this issue be closed out?

**Comment by jmesserly** [comment]
yes per @natebosch it was fixed. More info: https://github.com/dart-lang/sdk/issues/36264#issuecomment-474640754

**Comment by natebosch** [comment]
[Version `1.0.9`](https://pub.dartlang.org/packages/package_resolver/versions/1.0.9#-changelog-tab-) should work with the `2.1.0` SDK. It doesn't have imports conditional on `dart.library.isolate` and has a [compatible SDK constraint](https://github.com/dart-lang/package_resolver/blob/1.0.9/pubspec.yaml#L9).
