### ISSUE TITLE
Please publish the tip-of-tree, and update it in dart's DEPS

### ISSUE THREAD

**Issue by whesse** [dart-lang/package_resolver#3]
The test on MacOS is still failing on our buildbots, because the version with the fix has not been rolled into DEPS.  Please tag, upload to pub, and update in DEPS.

**Comment by whesse** [comment]
I just noticed the test is broken on Windows too.  Will the fix that was committed fix that too?

00:00 +52 -1: test\package_root_info_test.dart: packagePath with a file: scheme
  Expected: 'C:\\Users\\CHROME\~2\\AppData\\Local\\Temp\\package_resolver_test7fda2d5e-b709-11e6-b9ff-005056030208\\foo'
    Actual: 'C:\\Users\\chrome-bot\\AppData\\Local\\Temp\\package_resolver_test7fda2d5e-b709-11e6-b9ff-005056030208\\foo'
     Which: is different.
  Expected: ... :\\Users\\CHROME\~2\\ ...
    Actual: ... :\\Users\\chrome-bot ...
                          ^
   Differ at offset 11
  
  package:test                            expect
  test\package_root_info_test.dart 144:7  main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                              _Completer.completeError
  test\package_root_info_test.dart 146:6  main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                              _asyncThenWrapperHelper
  test\package_root_info_test.dart        main.<fn>.<fn>

**Comment by nex3** [comment]
Generally we don't publish package updates that only fix tests, since they don't provide any end-user value.

Why are we running tests of GitHub packages in the SDK repo at all? It seems like there should only be one canonical place to check for the tests for a given chunk of code—possibly excluding `pub`, since that's actually exported by the SDK.

**Comment by whesse** [comment]
We need at least a tag, to import it in DEPS, since we import by tag, not
hash. So please tag it and update deps.

We test the unit tests of packages used by the sdk, in the sdk checkout, so
that we check a package in the context of the versions of its dependencies
that are checked out in the repo.  This is much harder, nearly impossible,
unless we do it in the checkout, and easy to do in the checkout.  I also
think package_resolver is in third_party/package _tested.

This is the way that we found the bug in package_resolver, so I think it
has been useful.  So we need to start using the version with the bug fix,
so we can catch new bugs.

**Comment by kevmoo** [comment]
I think this is long stale...
