### ISSUE TITLE
Discontinue/deprecate/archive this package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/package_resolver#30]
Functionality the Dart team cares about seems to have been rolled into https://pub.dev/packages/package_config

14 packages used by Dart team: some published, some internal, etc
17 total users on pub: https://pub.dev/packages?q=dependency%3Apackage_resolver

- [x] migrate usages in SDK - https://github.com/dart-lang/sdk/commit/9f1fbd242be2b76930c6460210fcf4543dd632d2
- [x] migrate usages in other packages
  - [x] pub tool (dev dependency) – https://github.com/dart-lang/pub/blob/master/pubspec.yaml 
  - [x] 5 build packages - https://github.com/dart-lang/build/issues/2640
  - [x] dwds: https://github.com/dart-lang/webdev/issues/915
  - [x] pkg:reflectable - https://github.com/dart-lang/reflectable/issues/205
- [x] discontinue package on pub.dev - done! https://pub.dev/packages/package_resolver/
- [x] archive this package

CC @jakemac53 @lrhn

**Comment by jakemac53** [comment]
Nothing scary looking internally - almost all third_party deps (same ones as are on pub already)

**Comment by lrhn** [comment]
Be aware that the currently published version of `package_config` is not the one to use. We have modified the API since then, so the version to actually use will probably be 3.0.0. (Unless we need to change more things).

The current version is at the tip of the master branch (https://github.com/dart-lang/package_config/commit/96ea9163328c16fc28e1518ed1daf7352eb8769d) and is numbered 3.0.0-dev. It has not been published yet (because publishing 2.0.0 was a mistake, so let's not do that again immediately).

**Comment by jakemac53** [comment]
Oh ok, can we also look at https://github.com/dart-lang/tools/issues/1522 for 3.x @lrhn .

Fixing that also requires breaking changes.

**Comment by lrhn** [comment]
@jakemac53 Already fixed. The version currently used by the SDK has a `package_config_types.dart` library which does not depend on `dart:io`. The `package_config.dart` library exports that and the `dart:io` dependent load/save functions.

**Comment by kevmoo** [comment]
So the only Dart code using this is the `pub` client – and only a dev dependency


Grepping the SDK source

```
.dart_tool/package_config.json:481:      "name": "package_resolver",
.dart_tool/package_config.json:482:      "rootUri": "../third_party/pkg_tested/package_resolver",
.packages:77:package_resolver:third_party/pkg_tested/package_resolver/lib
DEPS:116:  "package_resolver_tag": "1.0.10",
DEPS:344:  Var("dart_root") + "/third_party/pkg_tested/package_resolver":
DEPS:345:      Var("dart_git") + "package_resolver.git"
DEPS:346:      + "@" + Var("package_resolver_tag"),
pkg/front_end/lib/src/fasta/source/source_library_builder.dart:479:    'package_resolver',
pkg/frontend_server/lib/frontend_server.dart:28:import 'package:package_resolver/package_resolver.dart';
pkg/frontend_server/lib/src/javascript_bundle.dart:13:import 'package:package_resolver/package_resolver.dart';
pkg/frontend_server/pubspec.yaml:16:  package_resolver: ^1.0.0
pkg/frontend_server/test/src/javascript_bundle_test.dart:13:import 'package:package_resolver/package_resolver.dart';
pkg/test_runner/lib/src/testing_servers.dart:9:import 'package:package_resolver/package_resolver.dart';
pkg/test_runner/pubspec.yaml:14:  package_resolver:
pkg/test_runner/pubspec.yaml:15:    path: ../../third_party/pkg_tested/package_resolver
runtime/observatory/.packages:24:package_resolver:../../third_party/pkg_tested/package_resolver/lib
tools/patches/flutter-engine/0299903f3e78ab6eb1d7d5ed1a70a039b3646913.patch:10:   'dart_package_resolver_tag': '1.0.10',
tools/patches/flutter-engine/6e2b3f0326bc15ad938319cbbb151f183d064609.patch:11:   'dart_package_resolver_tag': '1.0.10',
```

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/138322 for the frontend_server portion

**Comment by jakemac53** [comment]
Looks like the test_runner still supports a `packageRoot` argument - trying to see if it is actually in use though.

Trying out removing support here https://dart-review.googlesource.com/c/sdk/+/138324

**Comment by kevmoo** [comment]
Awesome work, @jakemac53 

```
.dart_tool/package_config.json:481:      "name": "package_resolver",
.dart_tool/package_config.json:482:      "rootUri": "../third_party/pkg_tested/package_resolver",
.packages:77:package_resolver:third_party/pkg_tested/package_resolver/lib
DEPS:116:  "package_resolver_tag": "1.0.10",
DEPS:344:  Var("dart_root") + "/third_party/pkg_tested/package_resolver":
DEPS:345:      Var("dart_git") + "package_resolver.git"
DEPS:346:      + "@" + Var("package_resolver_tag"),
pkg/front_end/lib/src/fasta/source/source_library_builder.dart:481:    'package_resolver',
runtime/observatory/.packages:24:package_resolver:../../third_party/pkg_tested/package_resolver/lib
```
Just need to clean up observatory deps and we can remove it entirely from the SDK?

**Comment by jakemac53** [comment]
Yep I was just starting to look at that

**Comment by jakemac53** [comment]
@kevmoo do you know about the `fasta` `optOutPackages` list that shows up there? can I safely remove it from that?

**Comment by jakemac53** [comment]
~https://dart-review.googlesource.com/c/sdk/+/138385 I went ahead and removed it from that list for now~ Abandoned as there are still third_party deps which vscode doesn't show for some reason when i search.

**Comment by jakemac53** [comment]
Looks like we are blocked on `pub` and `dart_style `removing their deps on this package, and then rolling in some new versions of a bunch of other deps:

- [x] source_map_stack_trace
- [x] test
- [x] test_core
- [x] shelf_packages_handler

**Comment by kevmoo** [comment]
Thanks for tracking this, @jakemac53 !

**Comment by jakemac53** [comment]
@kevmoo have you already filed any issues for pub/dart_style that you can link here or do we need to create those?

**Comment by kevmoo** [comment]
Have not filed issues on those

**Comment by jakemac53** [comment]
dart_style was a red herring just a transitive dep that shows up in the pubsepc.lock file

So it is really just pub.

**Comment by jakemac53** [comment]
@kevmoo build/webdev are now migrated off completely

**Comment by kevmoo** [comment]
`pkg:reflectable` is the last hold-out https://github.com/dart-lang/reflectable/issues/205

@mit-mit – do we want to move this to `dart-archive` org? It has the potential to break folks trying to build old SDKS.

I guess once 2.8 ships, it's less of an issue.

**Comment by mit-mit** [comment]
> @mit-mit – do we want to move this to dart-archive org? It has the potential to break folks trying to build old SDKS.

Sorry, how does moving the repo, and marking the package as deprecated on pub.dev, break anyone?

**Comment by eernstg** [comment]
Reflectable has been updated such that there is no dependency on `package_resolver`. However, `pub publish` currently crashes (cf. https://github.com/dart-lang/pub/issues/2410), so it cannot be published immediately.

**Comment by eernstg** [comment]
Reflectable 2.2.4 is has now been published.

**Comment by jakemac53** [comment]
> Sorry, how does moving the repo, and marking the package as deprecated on pub.dev, break anyone?

I think because old checkouts of the SDK still have a dependency on it, so `gclient sync` would probably fail? I am actually not sure though because it pulls from our mirror of the repo not the actual github repo, and I don't have any idea how long that would stay up after this repo is moved.

**Comment by mit-mit** [comment]
It's my understanding that github does redirects, e.g. https://github.com/dart-lang/rpc/ redirects to https://github.com/dart-archive/rpc, so that should work?

**Comment by jakemac53** [comment]
> It's my understanding that github does redirects, e.g. https://github.com/dart-lang/rpc/ redirects to https://github.com/dart-archive/rpc, so that should work?

We don't pull from github though, I don't know how our mirrors work or if they will be impacted. cc @sortie I think would know better

**Comment by kevmoo** [comment]
this is all about the internal clone for the SDK

I guess we can do the archive dance and see if anything breaks. Will do it now!
