### ISSUE TITLE
Create a branch for enabling http tests

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/package_resolver#4]
Currently there is a circular dependency between `test` and `http` caused by `package_resolver`. Pub no longer allows a package to depend on itself so `dependency_overrides` cannot be used to successfully install `test` within the `0.12.0-dev` version of `http`.

Please create a branch with the following changes so it can be used as an override within `http` until the dependency here can be loosened.

```
diff --git a/pubspec.yaml b/pubspec.yaml
index 05454ee..654b6c9 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -9,7 +9,7 @@ environment:

 dependencies:
   collection: '^1.9.0'
-  http: '^0.11.0'
+  http: '^0.12.0-dev'
   package_config: '>=0.1.0 <2.0.0'
   path: '^1.0.0'
 dev_dependencies:
```

**Comment by nex3** [comment]
This looks like #1443, which I thought had been fixed.

@donny-dont, can you open a PR for this branch of `package_resolver` for now?

**Comment by donny-dont** [comment]
I swore at one point that you COULD do this but it seems like pub changed to disallow that. Anyways I'll open up a branch on that.

**Comment by nex3** [comment]
Actually, I just re-tested, and it looks like this works:

```yaml
dependency_overrides:
  package_resolver: '^1.0.0'
```

**Comment by donny-dont** [comment]
@nex3 weird I see that it works as well. Preparing some tests for you to land. I'll do it like that.
